### ISSUE TITLE
Send and Clean commands not working

### ISSUE THREAD

**Issue by queenofeville** [SparkeyG/Botler#6]
Using the $record_start command (seems to) works fine. You see the Chat Logger respond with "<person> asked for <channel> to be recorded"

But when you type the $record_send command, it shows that Chat Logger is typing, but no text ever appears, nor does any email arrive at the destination. This is using either  '$record_send' or 'record_send send_to=<email>'.

Using the $room_clean command has the same effect. Chat logger is typing, but nothing appears on the screen and the channel is not cleaned.

Not sure what I did wrong in "installing" it. Is it possible that because I've changed servers it won't function properly? (We had to migrate servers due to ownership issues with the old one). (No clue if part of the code is somehow server specific or not.)

**Comment by SparkeyG** [comment]
Please try now. There were bugs.
